@startuml
actor 图书管理员
activate 图书管理员
图书管理员->管理员信息:登录
activate 管理员信息
管理员信息->图书管理员:允许登录
deactivate 管理员信息
activate 图书信息
opt 修改图书信息
    图书管理员->图书信息:获取图书信息
    图书信息->图书管理员:返回图书信息
    图书管理员->图书信息:修改图书信息
    图书信息->图书管理员:修改成功
end
opt 增加图书
    图书管理员->图书信息:添加图书信息
    图书信息->图书管理员:添加成功
end
deactivate 图书信息
deactivate 图书管理员
@enduml