@startuml
actor 学生
activate 学生
学生 ->学生信息:验证登录
activate 学生信息
学生信息 ->学生:验证成功
deactivate 学生信息
学生->图书信息:获取图书信息
activate 图书信息
图书信息 ->学生:返回图书信息
学生->预定图书信息:预定图书
activate 预定图书信息
预定图书信息->图书信息:图书剩余量是否可预定
loop 等待预定
    图书信息->预定图书信息:剩余量不足,并等待预定
    预定图书信息->学生:等待预定
end
图书信息->预定图书信息:剩余量可预定
deactivate 图书信息
预定图书信息->学生:预定成功
deactivate 预定图书信息
deactivate 学生
@enduml