@startuml
title 基于GitHub的实验管理平台--设定实验用例的顺序图
actor 教师
actor 系统
activate 教师
教师->系统:添加实验请求
activate 系统
系统->课程信息:查询当前教师课程信息
activate 课程信息
课程信息-->系统:返回当前教师课程信息
deactivate 课程信息
系统-->教师:返回可添加实验的课程
教师->系统:选择需要添加实验的课程
==添加实验信息==
系统-->教师:返回实验信息表
教师->系统:添加实验信息
系统->实验信息:存储数据
activate 实验信息
实验信息-->系统:存储成功
deactivate 实验信息
==添加评分细则信息==
系统-->教师:返回评分细则信息表
教师->系统:添加评分细则
系统->评分细则信息:存储数据
activate 评分细则信息
评分细则信息-->系统:存储成功
deactivate 评分细则信息
系统-->教师:添加课程成功
deactivate 系统
deactivate 教师
@enduml