@startuml
title 基于GitHub的实验管理平台--修改密码用例的顺序图
actor 用户
activate 用户
alt 如果用户为学生
    用户->学生信息:更改密码请求
    activate 学生信息
    学生信息-->用户:要求输入数据
    用户->学生信息:输入旧密码和新密码
    学生信息-->用户:核对输入合法性，并反馈结果
    deactivate 学生信息
else 如果用户为教师
    用户->教师信息:更改密码请求
    activate 教师信息
    教师信息-->用户:要求输入数据
    用户->教师信息:输入旧密码和新密码
    教师信息-->用户:核对输入合法性，并反馈结果
    deactivate 教师信息
else 如果用户为管理员
    用户->管理员信息:更改密码请求
    activate 管理员信息
    管理员信息-->用户:要求输入数据
    用户->管理员信息:输入旧密码和新密码
    管理员信息-->用户:核对输入合法性，并反馈结果
    deactivate 管理员信息
end
deactivate 用户
@enduml